# Data paths for harmful virus finetuning

train-data-paths:
  - '/workspace/bdt-finetuning-replication/data/harmful_tokenized/train_text_CharLevelTokenizer_document'
train-data-weights:
  - 1

valid-data-paths:
  - '/workspace/bdt-finetuning-replication/data/harmful_tokenized/test_text_CharLevelTokenizer_document'
valid-data-weights:
  - 1

test-data-paths:
  - '/workspace/bdt-finetuning-replication/data/harmful_tokenized/test_text_CharLevelTokenizer_document'
test-data-weights:
  - 1

checkpoint_validation_with_forward_pass: False
